### ISSUE TITLE
Reference to PFUNIT-4.0, not PFUNIT-4.1

### ISSUE THREAD

**Issue by bernienor** [Goddard-Fortran-Ecosystem/pFUnit_demos#3]
I've just build pFUnit (97ec8dc8e9dbc183a5b98c8378583195dca7a528) and tried to run the Trivial and Basic demos.
I had to update the reference to pFUnit from 4.0 to 4.1 in the makefiles:
`include $(PFUNIT_DIR)PFUNIT-4.1/include/PFUNIT.mk`

This is consistent in the following makefiles:
```
    Trivial/Makefile
    Basic/Makefile 
    Basic/tests/Makefile
    MPI/Makefile
    MPI/tests/Makefile
```

Could pFUnit maybe make a symbolic link : PFUNIT_DIR/PFUNIT pointing to the current version. Thus reducing the need for keeping pFUnit and pFUnit_demo synchronized.

**Comment by tclune** [comment]
Yes - checking out the master branch is probably more consistent with the intent of this project.

I ran into the issue myself a couple of weeks back and am a bit surprised I did not at  least do the 4.1 fix before your attempt.

**Comment by tclune** [comment]
Oh - not quite as easy as specifying the branch.    Did not have my caffeine yet.

I'll check to see if there is a way with CMake to do the symbolic link you want.   It's not obvious that there is a good way to do this, as CMake is the one that actually creates the PFUNIT-4.1 directory.   I'll also check to see if there is way just to get Make to find the lates version under PFUNIT_DIR.
